ALTER TABLE letter DROP CONSTRAINT IF EXISTS letter_kind_check;
ALTER TABLE letter ADD CONSTRAINT letter_kind_check CHECK (kind IN (
    'MESSAGE', 'CREDENTIAL_BUNDLE', 'FILE_ARCHIVE', 'ACTION',
    'WILL_LOCATOR', 'VIDEO_MESSAGE', 'AUDIO_MESSAGE', 'MEDIA_PLAYLIST'
));
