[package]
name = "beacon-api"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "beacon"
path = "src/main.rs"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
http-body-util.workspace = true
tower.workspace = true
tempfile.workspace = true
uuid.workspace = true
sqlx.workspace = true

[dependencies]
beacon-core.workspace = true
beacon-db.workspace = true
crypto-stub = { workspace = true, features = ["aws"] }
paschal-transform.workspace = true
blob-store = { workspace = true, features = ["aws"] }

tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
hyper.workspace = true

sqlx.workspace = true

serde.workspace = true
serde_json.workspace = true

uuid.workspace = true
chrono.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

thiserror.workspace = true
anyhow.workspace = true
hex.workspace = true
async-trait = "0.1"
rand.workspace = true
base64.workspace = true
sha2.workspace = true
hmac.workspace = true
subtle.workspace = true
include_dir.workspace = true
reqwest.workspace = true
lettre.workspace = true
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation", "resident-key-support"] }
url = "2"
